### PR TITLE
2021 Frontend Challenge Draft

### PR DESCRIPTION
**Pull request by ejmockler**
Github deleted my completed draft by refreshing the editor webpage, so here we go again..

### CODE REVIEW

**Review by floof-boi — APPROVED** [review]
Looks good so far!

**Comment by ejmockler** [comment]
Hopefully the challenge isn't too long-winded! I added some details regarding tests & form validation. Should be close to primetime now.

**Review by floof-boi — CHANGES_REQUESTED** [review]
Looks good - I really like how you linked a bunch of resources to help folks get started! I have a few minor syntactical comments:
1. On line 59, there's a missing space for the markdown for the 2nd link - so the text/words aren't linked!
2. I think there's a missing link on line 61 for Jest? 
3. Line 69 - looks like the second half of the sentence is missing

**Review by floof-boi — APPROVED** [review]
💯

**Pull request merged**
